name: Android CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

#      - name: Bump version code
#        uses: chkfung/android-version-actions@v1.2
#        with:
#          gradlePath: app/build.gradle.kts
#          versionCode: ${{github.run_number}}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleRelease

      - name: Generate Signed AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Create and push tag
        run: |
            git config --global user.email "swapnil.musale@mutualmobile.com"
            git config --global user.name "$GITHUB_ACTOR"
            
            git tag -a $TAG -m "Release v$TAG"
            git push origin $TAG
          env:
            TAG: ${{ github.event.inputs.versionName }}

      - name: Create Release on GitHub
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.versionName }}
          release_name: ${{ github.event.inputs.versionName }}
          draft: true
          prerelease: false